### ISSUE TITLE
Feature request: Opening files directly from command line

### ISSUE THREAD

**Issue by joerivan** [ifilot/atom-architect#9]
Users of Atom Architect might run the program directly from the command line. A feature making the program more user friendly would be to allow the input of a file path when starting Atom Architect to allow the program to directly open that particular file.

Allowing a tag like `-n` or `-g` (for NEB analysis and Geometry optimization analysis) could possible even directly open a file in one of the Analysis tabs.

**Comment by ifilot** [comment]
There are three command-line options now available:

1. `-n <nebpack.bin>`: Opens NEB Analysis window and loads the file `nebpack.bin`
2. `-g <OUTCAR>`: Opens a Geometry Analysis window and loads the file `OUTCAR`
3. `-o <file>`: Opens a general structure file into the regular window
